### ISSUE TITLE
Is it possible to rename a unit? (and other options)

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#593] opened 2018-10-16 01:32 UTC
Made several units with a typo (Made a bug in my bug testing scripts 😅 ), and wanted to rename some units to fix it. Realised that there doesn't seem to be possible. Not too sure if this is a feature or UX issue.

This applies to additional properties such as "Additional Description"

Page where I expected some way to edit
![screen shot 2018-10-16 at 9 33 26 am](https://user-images.githubusercontent.com/17175484/46987384-92ffcc00-d126-11e8-9293-ee140767f64f.png)

Also related : how to disable a unit? (since I do see a listing tab for disabled unit)

**Comment by franck-boullier** [comment] 2019-01-03 20:08
this is a duplicate of #352

**Closed by franck-boullier** 2019-01-03 20:08 UTC
Labels: Feature
