### ISSUE TITLE
Open image in a case - back button leads to a blank page

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#668] opened 2018-12-11 01:45 UTC
# The problem:

Tested of FF on a desktop in the DEV/Staging):
- log in as leonel
- Open a case (https://case.dev.unee-t.com/case/41)
- Click on the image
- Click on the back button on top of the image

### Option 1: 
User is sent back to the case conversation if user clicks on the image in the conversation

### Option 2: 
User is sent back to the case details if user clicks on the image in the case details

## Actual result:

For either option 1 and option 2 the user sees a white page.
Note the URL of the page which is https://case.dev.unee-t.com/case/41/attachment. 
The working url for this case are 
- https://case.dev.unee-t.com/case/41 (conversation page)
or
- https://case.dev.unee-t.com/case/41/details (details page)

![image](https://user-images.githubusercontent.com/31331637/49772614-dfcbe180-fd28-11e8-9aa8-81db8a4c80b0.png)

@nbiton this is probably one for you...

Marking this as critical as this prevents us from pushing the current master in the PROD environment.

**Comment by kaihendry** [comment] 2018-12-11 02:21
What was the leonel username? https://s.natalian.org/2018-12-11/1544494877_2558x1406.png

Failing to login.

**Comment by kaihendry** [comment] 2018-12-11 03:00
Reproduced the issue here: https://media.dev.unee-t.com/2018-12-11/668.mp4
@nbiton btw you should be using **f_auto** for the full size image.

**Comment by nbiton** [comment] 2018-12-12 04:52
Duplicate of #267 .
@kaihendry I'm closing this as duplicate, so let's track other issues separately.

**Closed by nbiton** 2018-12-12 04:52 UTC
Labels: bug, critical
