### ISSUE TITLE
Case listing shows "extra numbers" after the unit name

### ISSUE THREAD

**Issue by PicoCreator** [unee-t/frontend#594] opened 2018-10-16 04:32 UTC
**Tested on:** Chrome & Firefox, Dev & Demo environment

![screen shot 2018-10-16 at 12 23 27 pm](https://user-images.githubusercontent.com/17175484/46992974-5a202100-d13f-11e8-8c8f-bd52df10a822.png)

Unit : "Demo Unit - 13-06"
Case : "Demo Unit - 13-06-556" (expected without the -556)

**Comment by franck-boullier** [comment] 2018-10-16 09:15
this is a duplicate of issue #394

**Closed by franck-boullier** 2018-10-16 09:15 UTC
