### ISSUE TITLE
Include more information in the invitation email

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/frontend#113] opened 2018-02-06 19:22 UTC
In PR #111 the invitation is too dry and not informative and personal enough. The risk is that the invitee will consider the email as spam and ignore it.

We should include the following information that we already have in Unee-T to increase the chances that the invitor clicks on the invitation link:
- [Case Title]: the title of the case
- [Unit Name]: Name of the unit/product
- [Unit Description]: Description of the unit, including the address, this is so that the invitee can recognize the unit.
- [Invitor Username]: The Invitor username
- [Invitor email address]: The invitor email address
- [Invitor Role in the Unit]: The  role of the invitor in that unit.
- [Invitee Role in the Unit]: The role of the invited user as declared by the invitor.

In the file imports/util/email-invite.js
The text of the email could be something like this:

---
Subject: New Case: [Case title]
Text: [Invitor Username] ([Invitor email address]), the [Invitor Role in the Unit] for the Unit [Unit Name] ([Unit Description]) has invited you to collaborate on the case [Case Title] as the [Invitee Role in the Unit] for that unit.
Please click the link below to get more information about the case and reply to [Invitor Username] :
[include the magic link]
Best regards,
The Unee-Team

To learn more about Unee-T, [visit our website](https://unee-t.com/)

---

**Comment by kaihendry** [comment] 2018-02-07 05:53
IMO, the most personal/appealing thing you can do is putting a real name in the From: field instead of 'Unee-T Case' or 'The Unee-Team'. Especially when you are starting out.

I want to see https://github.com/unee-t/frontend/pull/111 merged before working on this.

**Comment by nbiton** [comment] 2018-02-07 06:17
The Case title needs to be retrieved with the case object from BZ API.
Unit name/description + Invitor/invitee roles  -> unit from BZ API.
Invitor username + email address -> mongo query on users.

**Comment by franck-boullier** [comment] 2018-02-07 07:56
"I want to see #111 merged before working on this."
@kaihendry Can you elaborate why do you feel that this issue is not relevant to PR #111 ?

**Comment by franck-boullier** [comment] 2018-02-07 08:06
"IMO, the most personal/appealing thing you can do is putting a real name in the From: field instead of 'Unee-T Case' or 'The Unee-Team'. Especially when you are starting out."

@kaihendry I take your point but I disagree with it for several reason:
- Unee-T is not a single man project and I see no reason why we should use my name instead of someone else's -> I have no good answer to the question 'Which person's name should we use then?'
- Using a single person names gives the impression that only one person is in charge: this is NOT the impression that I want users to have. I want user to have the perception that this is a professional application that is supported by more than 1 person.
- Hard coding a name (even in an environment variable) means that we need to redeploy each time that name changes (and it WILL change as we grow). Hard coding a Role or generic identifier is something that can be relevant for much longer.
- Using my name (or someone else's name) will not give a 'personalized message' feeling to any of the user except those who know who I am. The vast majority of users will NOT know who I am. Getting relevant information to the user is what makes it personal.

**Comment by kaihendry** [comment] 2018-02-09 01:15
The issue is relevant to https://github.com/unee-t/frontend/pull/111 though I just wanted to make sure the basic mechanism is in place before adding complexity to the template.

@nbiton Need to chat to you to work out how get that info from the BZ API

Another idea: a montage of the image uploads associated with the case as header in the HTML email counterpart. If there is one thing I know, a "Picture Worth Ten Thousand Words"

**Comment by kaihendry** [comment] 2018-02-09 06:07
For case data:
`const caseData = callAPI('get', `/rest/bug/${caseId}`, {token}, false, true)`

For unit description:

      url: '/rest/product',
      params: {ids: unidId}

**Closed** 2018-02-15 10:55 UTC
Labels: Pilot
