### ISSUE TITLE
Prevent multiple sending of the signup verification email

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#659] opened 2018-12-05 09:05 UTC
We just saw it being sent 3 times on a new user signup (Andrew)

**Comment by kaihendry** [comment] 2018-12-06 09:48
As discussed over Slack, this is likely to do with some multi clicks of the register button ?

I can't [find any logs of the email being sent out](https://s.natalian.org/2018-12-06/1544089606_2558x1406.png), so it would be good some logging could be added to Meteor Accounts email.js to at least be able to see these actions taking place.

**Comment by kaihendry** [comment] 2019-01-04 03:02
Couldn't reproduce so closing.

**Closed by kaihendry** 2019-01-04 03:02 UTC
