### ISSUE TITLE
First unit form

### ISSUE THREAD

**Issue by nbiton** [unee-t/frontend#7] opened 2017-09-21 03:54 UTC

**Comment by franck-boullier** [comment] 2017-09-21 04:06
Heads up, creating a new unit means that we will have to also create groups in the BZ backend.
I had a chat with @sebdeckers yesterday about that...
If I remember well, there was no BZ API available to create/manage groups.
We'll have to see how we can best handle that.

Refer to the gitlab repo https://gitlab.com/unee-t/sql_BZ_to_Unee-t_dev for what we created back in the days...
This should give you some understanding of what's needed when we create a new unit/user...

This is not set in stone and we probably need to have a chat about that as groups will have a significant impact on who can see what/do what/view what (inlcuding other users...)

**Comment by nbiton** [comment] 2017-09-21 04:56
I've looked into the repo, and it does seem a bit complicated, however, I could find this API for creating groups: 
http://bugzilla.readthedocs.io/en/latest/api/core/v1/group.html#create-group

This is the same documentation resource I used so far for integrating with the API, and the calls work as documented.

**Comment by franck-boullier** [comment] 2017-09-21 13:24
Excellent news!

**Comment by franck-boullier** [comment] 2018-04-11 00:47
this is a duplicate of issue #145 
Also the API referenced by @nbiton is experimental and not usable today in our current BZ implementation.

Closing this issue to centralize all the conversation around this in issue #145

**Closed** 2018-06-09 02:44 UTC
