### ISSUE TITLE
Marvin not being notified in demo env

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#728] opened 2019-03-08 08:23 UTC
test+marvin@case.demo.unee-t.com is verified in the demo env. `db.users.findOne({"emails.address": "test+marvin@case.demo.unee-t.com"})`

https://media.dev.unee-t.com/2019-03-08/marvin-notification.mp4

For picking up mail, the credentials are stored in demo's parameter store:
* TESTMAIL_HOST
* TESTMAIL_USER
* TESTMAIL_PASS

Maybe I didn't assign the case correctly? I think there might be an issue with [changes to the JSON payload](https://github.com/unee-t/bz-database/issues/118) (ints not quoted?) since there is **400** here:

<img src="https://s.natalian.org/2019-03-08/1552033273_2560x1440.png">

```
{
  "case_id": 2459,
  "unit_id": 3911,
  "case_title": "ABC is broken",
  "current_status": "CONFIRMED",
  "bz_source_table": "ut_notification_case_new",
  "notification_id": "ut_notification_case_new-2459",
  "assignee_user_id": 7,
  "created_datetime": "2019-03-08 08:07:05.000000",
  "current_severity": "normal",
  "reporter_user_id": 7,
  "notification_type": "case_new",
  "current_resolution ": ""
}
```

**Comment by franck-boullier** [comment] 2019-03-11 01:59
@nbiton and @kaihendry if the issue is with the new format of the payload this means that the DB schema change that I'm about to push in production WILL make the notification mechanism unstable in the PROD envo too ---> we probably need a quick fix for this so that the notifications are working well when the new DB schema is rolled out in PROD.

**Comment by nbiton** [comment] 2019-03-11 03:15
Closed as the root cause of this symptom is addressed in #729

**Comment by franck-boullier** [comment] 2019-03-11 05:09
> Closed as the root cause of this symptom is addressed in #729

I think this is incorrect: In the scenario, Marvin is assigned to the case i.e notification type `case_assignee_updated` ---> this is a different type of notification than `case_new` (#729)

**Comment by franck-boullier** [comment] 2019-03-11 05:12
We might be in a specific scenario here because Marvin is the INITIAL assignee for the case ---> in that scenario maybe the `case_assignee_updated` notification is not triggered since the case was not technically updated but created there?
I'll have a look into that too...
 🤔 ...

**Comment by franck-boullier** [comment] 2019-03-11 05:15
Just checked: notification `case_new` is the right notification type there and yes, the solution is to fix #729

**Comment by franck-boullier** [comment] 2019-03-11 05:20
incorrectly closed

**Comment by nbiton** [comment] 2019-03-11 07:12
Why was it reopened? Isn't it easier to track the issue via just #729 that pinpoints the problem more clearly?

**Comment by franck-boullier** [comment] 2019-03-11 07:38
OK closing...

**Closed by franck-boullier** 2019-03-11 07:38 UTC
